[run_config]
current_chain = "base_goerli"
account_owner = "0x245d2f541e3af7541241e3A0EA551187b165016B"
paymaster_account_owner = "0x245d2f541e3af7541241e3A0EA551187b165016B"
deployed_by_identifier = "toad.cash"
transaction_id_prefix = "toad"

[server]
port = "9010"
host = "0.0.0.0"
prefix = "stg"

[log]
level = "info"

[chains.sepolia]
chain_id = 11155111
url = "https://sepolia.infura.io/v3/"
explorer_url = "https://sepolia.etherscan.io/tx/"
simple_account_factory_address = "0xB6C7963d2aB527b79842214160683f953bD8998b"
usdc_address = "0xFa38B962562DF7F9eeD9d8Db3cC261053EFC263B"
entrypoint_address = "0x53D5E11475f4158dA8f0f3B46C69C717EE1b57b4"
verifying_paymaster_address = "0xe76cF38641112f77A474c467546Fb4b812e4d0F8"
currency = "SepoliaETH"

[chains.base_goerli]
chain_id = 84531
url = "https://wild-fluent-hill.base-goerli.quiknode.pro/"
explorer_url = "https://goerli.basescan.org/tx/"
simple_account_factory_address = "0xE437C8A95545443e357Be3bdE7Cf9bc1B4922a29"
usdc_address = "0x7e9b4b2B597DA00C5e7b2E95Dc34c408a7173B17"
currency = "ETH"
entrypoint_address = "0x5277533753B1AfE41FDEB7E7Baf46c242A38dEf7"
verifying_paymaster_address = "0x12Ee5b8ddD68DCF899B7e4776E0114fee55cBcDa"

[default_gas]
call_gas_limit = 10000000
verification_gas_limit = 10000000
pre_verification_gas = 1000000000000000
max_fee_per_gas = 5
max_priority_fee_per_gas = 1000000000
